version: "3.4"

services:

  # ----------------------------  
  # BROKER
  # ----------------------------
  broker-emqx:
    container_name: broker-emqx
    hostname: broker-emqx
    image: emqx/emqx-edge:4.2.7
    restart: always
    environment:
      - EMQX_LOADED_PLUGINS="emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
      - EMQX_NAME= emqx1
      - EMQX_ADMIN_PASSWORD= epyois100%MAGIC
      - EMQX_MQTT__MAX_PACKET_SIZE=${EMQX_MAX_PACKET_SIZE:-40MB}
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
    ports:
      - 1883:1883   # tcp
      - 8083:8083   # ws
      - 8883:8883   # tcp ssl
      - '127.0.0.1:18083:18083' # dashboard
      - '127.0.0.1:8081:8081'   # Api http

  # ---------------------------------
  # INFLUXDB
  # ---------------------------------
  tsdb:
    container_name: tsdb
    hostname: tsdb
    image: influxdb:1.8.4-alpine
    restart: always
    ports: 
      - '127.0.0.1:8086:8086'
    environment:
      - INFLUXDB_DB=epyo
      - INFLUXDB_HTTP_AUTH_ENABLED
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME:-epyo}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD:-epyois100%MAGIC}
    volumes:
      - vol-tsdb-data:/var/lib/influxdb
    
  chronograf:
    container_name: chronograf
    image: chronograf:1.8.8-alpine
    restart: always
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - vol-chronograf-data:/var/lib/chronograf
    depends_on:
      - tsdb
    environment:
      - INFLUXDB_URL=http://tsdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME:-epyo}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-epyois100%MAGIC}
  
  # ---------------------------------
  # Docker management
  # ---------------------------------
  # portainer:
  #   image: portainer/portainer:1.24.1-alpine
  #   container_name: portainer
  #   volumes: 
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - vol-portainer-data:/data
  #   ports:
  #     - '127.0.0.1:9000:9000'
  #   restart: always

volumes:
  vol-emqx-data:
    driver: local
  vol-emqx-etc:
    driver: local
  vol-emqx-log:
    driver: local
  vol-tsdb-data:
    driver: local
  vol-chronograf-data:
    driver: local
  
  # vol-portainer-data:
  #   driver: local